---

- name: create grafana.ini
  template:
    src: "grafana/grafana.ini.j2"
    dest: "{{ grafana_config_dir }}/grafana.ini"
    force: true
    owner: root
    group: "{{ grafana_system_group }}"
    mode: 0664
  notify:
    - validate config
    - reload grafana

- name: create ldap.toml
  template:
    src: "grafana/ldap.toml.j2"
    dest: "{{ grafana_config_dir }}/ldap.toml"
    force: true
    owner: root
    group: "{{ grafana_system_group }}"
    mode: 0664
  notify:
    - validate config
    - reload grafana

- name: restart grafana if needed
  meta: flush_handlers

# - name: api
#   include_tasks: configure/api.yml
#   when:
#     - grafana_api is defined
#     - grafana_api.keys is defined
#     # - grafana_api.keys | default([]) | count > 0

- name: datasources
  include_tasks: configure/datasources.yml
  when:
    - grafana_datasources | default({}) | count > 0

- name: plugins
  include_tasks: configure/plugins.yml
  when:
    - grafana_plugins | default([]) | count > 0

# - name: notifications
#   include_tasks: configure/notifications.yml
#   when:
#     - grafana_alert_notifications | default([]) | count > 0

...
