---

- name: ensure that {{ grafana_config_dir }} exists
  file:
    state: directory
    path: "{{ grafana_config_dir }}"
    owner: root
    group: "{{ grafana_system_group }}"
    mode: 0755

- name: create grafana.ini
  template:
    src: "grafana/grafana.ini.j2"
    dest: "{{ grafana_config_dir }}/grafana.ini"
    force: true
    owner: root
    group: "{{ grafana_system_group }}"
    mode: 0640
  notify:
    - validate config
    - restart grafana

- name: create ldap.toml
  template:
    src: "grafana/ldap.toml.j2"
    dest: "{{ grafana_config_dir }}/ldap.toml"
    force: true
    owner: root
    group: "{{ grafana_system_group }}"
    mode: 0640
  when:
    - grafana_config_auth is defined
    - grafana_config_auth.ldap is defined
    - grafana_config_auth.ldap.enabled | default('false') | bool
  notify:
    - validate config
    - restart grafana

- name: api
  include_tasks: configure/api.yml
  when:
    - grafana_api is defined
    - grafana_api.keys is defined
    # - grafana_api.keys | default([]) | count > 0

# - name: datasources
#   include_tasks: configure/datasources.yml
#   when:
#     - grafana_datasources | default({}) | count > 0
#
# - name: plugins
#   include_tasks: configure/plugins.yml
#   when:
#     - grafana_plugins | default([]) | count > 0

# - name: notifications
#   include_tasks: configure/notifications.yml
#   when:
#     - grafana_alert_notifications | default([]) | count > 0

...
