---

- name: prepare
  include_tasks: prepare.yml

#- name: download
#  include_tasks: download.yml
#  when:
#    - not stat_grafana_binary.stat.exists

#- name: install
#  include_tasks: install.yml

- name: configure
  include_tasks: configure.yml

#- name: service
#  include_tasks: service.yml

...
