---

grafana_version: 9.3.0

# enterprise or oss
grafana_edition: oss

grafana_provisioning:
  # Should we use the provisioning capability when possible (provisioning require grafana >= 5.0)
  enabled: false

grafana_api:
  # API keys to configure
  keys:
    - name: foo
      role: Viewer
      state: present
    - name: bar
      role: Editor
      state: absent
    - name: foobar
      role: Viewer
      state: absent
  # The location where the keys should be stored.
  store_directory: "{{ lookup('env', 'HOME') }}/grafana/keys"

# grafana_datasources:
#   prometheus:
#     # state: absent
#     type: "prometheus"
#     access: "proxy"
#     url: "http://prometheus.mydomain"
#     basicAuth: true
#     basicAuthUser: "admin"
#     basicAuthPassword: "password"
#     isDefault: true
#     jsonData:
#       tlsAuth: false
#       tlsAuthWithCACert: false
#       tlsSkipVerify: true

...
