---

grafana_version: 9.3.0

# enterprise or oss
grafana_edition: oss

grafana_provisioning:
  # Should we use the provisioning capability when possible (provisioning require grafana >= 5.0)
  enabled: false

grafana_api: {}

grafana_service_accounts: {}

grafana_plugins:
  - grafana-worldmap-panel
  - marcusolsson-gantt-panel

grafana_organisations:
  molecule: {}

grafana_datasources:
  #
  prometheus:
    # state: absent
    datasource:
      type: "prometheus"
      # access: "proxy"
      url: "http://prometheus.mydomain"
    # basic_auth:
    #   # Auth: true
    #   username: "admin"
    #   password: "password"
    default: true
    # json_data:
    #   tlsAuth: false
    #   tlsAuthWithCACert: false
    #   tlsSkipVerify: true

  loki:
    datasource:
      type: "loki"
      url: "http://loki.cmsops.arri.com"
    editable: true

...
