---

- name: restart grafana
  become: true
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: reload grafana
  become: true
  ansible.builtin.service:
    name: grafana-server
    state: reloaded

- name: validate config
  ansible.builtin.command: /bin/true

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"
  notify:
    - restart grafana

...
