---

name: code linter

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'main'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "tasks/**"
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "tasks/**"


defaults:
  run:
    working-directory: 'ansible-grafana'

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          path: 'ansible-grafana'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          yamllint .
          ansible-lint .
          flake8 .

      # - name: lint
      #   uses: docker://ghcr.io/github/super-linter:slim-v4
      #   env:
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
      #     VALIDATE_ALL_CODEBASE: true
      #     VALIDATE_ANSIBLE: true
      #     # VALIDATE_MARKDOWN: true
      #     VALIDATE_YAML: true

...
